# Generated by Django 5.0.1 on 2024-04-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='moreinformation',
            name='usersCar',
            field=models.ManyToManyField(to='SystemLogin.userscars'),
        ),
    ]
