# Generated by Django 5.0.1 on 2024-04-23 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0002_userscars_moreinformation_userscar'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinformation',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
