# Generated by Django 5.0.1 on 2024-04-28 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0004_remove_moreinformation_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moreinformation',
            old_name='model',
            new_name='property',
        ),
        migrations.AddField(
            model_name='moreinformation',
            name='vin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moreinformation',
            name='year',
            field=models.IntegerField(max_length=255),
        ),
    ]
