# Generated by Django 5.0.1 on 2024-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0005_rename_model_moreinformation_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinformation',
            name='year',
            field=models.IntegerField(),
        ),
    ]
