# Generated by Django 4.2.8 on 2024-07-08 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0006_alter_moreinformation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinformation',
            name='usersCar',
        ),
        migrations.AddField(
            model_name='moreinformation',
            name='code_filter_air',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moreinformation',
            name='code_filter_oil',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
