# Generated by Django 4.2.8 on 2024-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0007_remove_moreinformation_userscar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinformation',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moreinformation',
            name='technique_revision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
