# Generated by Django 4.2.8 on 2024-07-08 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfChangeOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_chevron', models.FloatField()),
                ('oil_havoline', models.FloatField()),
                ('air_filter', models.FloatField()),
                ('oil_filter', models.FloatField()),
                ('fuel_filter', models.FloatField()),
                ('water_trap', models.FloatField()),
            ],
            options={
                'verbose_name': 'PriceOfChangeOil',
                'verbose_name_plural': 'PricesOfChangeOils',
            },
        ),
        migrations.CreateModel(
            name='TotalPaidOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('date', models.DateField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TotalPaidOil',
                'verbose_name_plural': 'TotalPaidsOil',
            },
        ),
        migrations.CreateModel(
            name='KMCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_use', models.CharField(max_length=255)),
                ('km_today', models.FloatField(default=0)),
                ('total_journey', models.FloatField(default=0)),
                ('date', models.DateField(default=True)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KMCar',
                'verbose_name_plural': 'KMCars',
            },
        ),
    ]
