# Generated by Django 4.2.8 on 2024-07-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmcar',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
        ),
    ]
