# Generated by Django 5.0.1 on 2024-04-23 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmcar',
            name='user_use',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
