# Generated by Django 4.2.8 on 2024-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePrincipal', '0002_alter_kmcar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmcar',
            name='date',
            field=models.DateField(),
        ),
    ]
