# Generated by Django 4.2.8 on 2024-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
