# Generated by Django 4.2.8 on 2024-07-13 00:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_alter_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
        ),
    ]
