# Generated by Django 4.2.8 on 2024-07-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_expenses_description_alter_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
