# Generated by Django 4.2.8 on 2024-08-11 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0006_alter_expenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 11)),
        ),
    ]
