# Generated by Django 4.2.8 on 2024-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
